[tool.poetry]
name = "libb"
version = "0.1.0"
readme = "README.md"
description = "libb utility modules for python"
authors = ["bissli"]
license = "0BSD"

[tool.poetry.dependencies]
python = "~3.11"

python-dateutil = "*"
chardet = "*"
mailchimp-transactional = "*"
more-itertools = "*"
ftfy = "*"
regex = "*"
numpy = "*"
pandas-market-calendars = "*"
matplotlib = "*"
tzlocal = "*"
wrapt = "*"
paramiko = "*"
service-identity = "^24.1.0"

"web.py" = { version = "*", optional = true }
Flask = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
pre-commit = "*"
asserts = "*"
bump2version = "*"
pytest = "*"
pytest-runner = "*"
WebTest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
