[tool.poetry]
name = "libb"
version = "0.1.0"
readme = "README.md"
description = "libb utility modules for python"
authors = ["bissli"]
license = "0BSD"

[tool.poetry.dependencies]
python = "~3.11"

numpy = "*"
pandas-market-calendars = "*"
matplotlib = "*"
python-dateutil = "^2.8.2"
chardet = "^5.2.0"
more-itertools = "^10.2.0"
ftfy = "^6.1.3"
regex = "^2023.12.25"
tzlocal = "^5.2"
wrapt = "^1.16.0"
paramiko = "^3.4.0"
service-identity = "^24.1.0"

"web.py" = { version = "^0.62", optional = true }
Flask = { version = "^3.0.2", optional = true }
mailchimp-transactional = {version = "^1.0.56", optional = true }

[tool.poetry.dev-dependencies]
asserts = "^0.12.0"
pytest = "^8.0.0"
pytest-runner = "^6.0.1"
WebTest = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
