[tool.poetry]
name = "libb"
version = "0.1.0"
readme = "README.md"
description = "libb utility modules for python"
authors = ["bissli"]
license = "0BSD"

[tool.poetry.dependencies]
python = "~3.11"

python-dateutil = "^2.8.2"
chardet = "^5.2.0"
mailchimp-transactional = "^1.0.50"
more-itertools = "^10.1.0"
ftfy = "^6.1.1"

WebTest = { version = "^3.0.0", optional = true }
pytest = { version = "^7.4.2", optional = true }
"web.py" = { version = "^0.62", optional = true }
Flask = { version = "2.2.3", optional = true }
pytest-runner = { version = "^6.0.0", optional = true }
regex = "^2023.12.25"
numpy = "^1.26.3"
pandas-market-calendars = "^4.3.3"
matplotlib = "^3.8.2"

[tool.poetry.dev-dependencies]
pre-commit = "^3.4.0"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
