[tool.poetry]
name = "libb"
version = "0.1.0"
readme = "README.md"
description = "libb utility modules for python"
authors = ["bissli"]
license = "0BSD"

[tool.poetry.dependencies]
python = "~3.11"
poet-plugin = { git = "https://github.com/bissli/poet-exclusive-groups-plugin" }

numpy = "*"
matplotlib = "*"
more-itertools = "^10.2.0"
wrapt = "^1.16.0"
paramiko = "^3.4.0"
# == date
python-dateutil = "^2.8.2"
pandas-market-calendars = "*"
tzlocal = "^5.2"
# == text
regex = "^2023.12.25"
rapidfuzz = "^3.6.1"
ftfy = "^6.1.3"
chardet = "^5.2.0"

[tool.poetry.group.dev.dependencies]
# == Test
asserts = "^0.12.0"
pytest = "^8.0.0"
pytest-mock = "^3.12.0"
pytest-runner = "^6.0.1"
WebTest = "^3.0.0"
# == Misc
Twisted = "^23.8.0"
service-identity = "^24.1.0"
"web.py" = "^0.62"
Flask = "^3.0.2"
mailchimp-transactional = "^1.0.56"
pdbpp = { git = "https://github.com/pdbpp/pdbpp.git" }
black = "^23.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
